server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: microservicios

  application:
    name: CALIFICACION-SERVICE

  config:
    enabled: true
    import: optional:configserver:http://localhost:8085