server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservicios
    username: postgres
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  application:
    name: HOTEL-SERVICE

  config:
    import: optional:configserver:http://localhost:8085